TR001 criaçao da entidade Lead
sr-rafaelneves/treinarecife pull request #1
Opened 2022-11-17 23:38 UTC by flavioxenta

2022-11-17 23:52 UTC, alexandresjunior commented on backend/src/main/java/br/com/treinarecife/projetotreinarecife/model/Lead.java
> +
falta definir essa classe como entidade no banco de dados com a anotação `@Entity`.
trocar o nome da classe ou definir um nome específico com a anotação `@Table(name = "tb_lead")`, pois caso contrário, essa tabela não é criada no banco MySQL, pois `lead` é uma palavra-chave do MySQL (nome de uma função).

2022-11-17 23:53 UTC, alexandresjunior commented on backend/src/main/java/br/com/treinarecife/projetotreinarecife/model/Lead.java
> +    private Integer idLead;
definir esse atributo como chave primário com a anotação:
```
@Id 
@GeneratedValue(strategy = GeneratedType.AUTO)
```

além disso, para a chave primária da própria entidade pode-se utilizar apenas o nome `id`. para chaves estrangeiras, usa-se `id`+`nome da entidade`.

2022-11-17 23:55 UTC, alexandresjunior requested changes
solicitações de mudanças acrescentadas nos comentários.

2022-11-22 22:21 UTC, sr-rafaelneves approved these changes
Xenta a TR001 está ok.

2022-11-22 23:52 UTC, merged